<?php

$config = array(
	'Application' => array(
		'name' 	  => 'CakeStrap',
		'version' => 'v0.7',
		'status'  => false,
		'maintenance' => 0
	),
	'Meta' => array(
		'title' 	  => '{{title}}',
		'description' => '{{description}}',
		'keywords' 	  => '{{keywords}}',
	),
	
	'Google' => array(
		'analytics'  => '{{analytics}}',
	),
	
	'Email' => array(
		'from_email' => array('{{from_name}}' => '{{from_email}}'),
		'contact_mail' => array('{{contact_name}}' => '{{contact_mail}}')
	)
);

?>
